/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospital.management.system;

import Project.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yogesh Nirwal
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private String setlog;
    public static frontPage flog;
//    private String setlog1="addmin";

    public Login() {
        initComponents();
        jButton3.setVisible(false);
        jLabel3.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 78, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 78, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 280, 30));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 280, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/image_search_1705495282418 (1).png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 120, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Addmin Login");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Sign Up");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 111, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 101, 78, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Last Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 102, 78, 28));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Contact Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 134, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 101, 185, 30));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 101, 202, 30));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 280, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/pimage.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setlogin(String str, frontPage flogin) {
        setlog = str;
//        flog = flogin;

    }

    static void closeFlogin(frontPage flogin) {
        flog = flogin;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        if(jTextField1.getText().equals("Yogesh Nirwal")&& jPasswordField1.getText().equals("Yogesh9084")){
//        setVisible(false);
//        new Home().setVisible(true);
//        }
//        else
//            JOptionPane.showMessageDialog(null,"Incorrect username or password");
//          
        String username = jTextField1.getText();
        String password = jPasswordField1.getText();
        if (null != setlog) {
            switch (setlog) {
                case "addmin" -> {
                    try {
                        Connection con = ConnectionProvider.getcon();
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery("select * from addminlogin where username='" + username + "' AND password='" + password + "'");

                        if (rs.next()) {
                            Home dr = new Home();

                            setVisible(false);
                            flog.setVisible(false);
                            dr.setVisible(true);

                        } else if ((jTextField1.getText().length() == 0) || (jPasswordField1.getText().length() == 0)) {
                            JOptionPane.showMessageDialog(null, "Entry Field is empty");
                        } else {
                            JOptionPane.showMessageDialog(null, "Incorrect username or password");
                            jTextField1.setText("");
                            jPasswordField1.setText("");
                        }

                    } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "Login Successfully");
                    }
                }
                case "Doctor" -> {
                    try {
                        Connection con = ConnectionProvider.getcon();
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery("select * from doctors where username='" + username + "' AND password='" + password + "'");

                        if (rs.next()) {

                            setVisible(false);
                            flog.setVisible(false);
                            Home dr = new Home();
                            dr.jButton4.setVisible(false);
                            dr.jButton5.setVisible(false);
                            dr.jButton9.setVisible(false);
                            dr.jButton11.setVisible(false);
                            dr.setappoint(rs.getString(1));
                            dr.setHome("Doctor");

                            dr.setVisible(true);

                        } else if ((jTextField1.getText().length() == 0) || (jPasswordField1.getText().length() == 0)) {
                            JOptionPane.showMessageDialog(null, "Entry Field is empty");
                        } else {
                            JOptionPane.showMessageDialog(null, "Incorrect username or password");
                            jTextField1.setText("");
                            jPasswordField1.setText("");
                        }

                    } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "Login Successfully");
                    }
                }
                case "Receptionist" -> {
                    try {
                        Connection con = ConnectionProvider.getcon();
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery("select * from Receptionists where username='" + username + "' AND password='" + password + "'");

                        if (rs.next()) {

                            setVisible(false);
                            flog.setVisible(false);
                            Home dr = new Home();

                            dr.jButton4.setVisible(false);
                            dr.jButton5.setVisible(false);
                            dr.jButton2.setVisible(false);
                            dr.setHome("Receptionist");
                            dr.setVisible(true);

                        } else if ((jTextField1.getText().length() == 0) || (jPasswordField1.getText().length() == 0)) {
                            JOptionPane.showMessageDialog(null, "Entry Field is empty");
                        } else {
                            JOptionPane.showMessageDialog(null, "Incorrect username or password");
                            jTextField1.setText("");
                            jPasswordField1.setText("");
                        }

                    } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "Login Successfully");
                    }
                }
                case "Patient" -> {
                    try {
                        Connection con = ConnectionProvider.getcon();
                        Statement st = con.createStatement();
                        ResultSet rs = st.executeQuery("select * from userlogin where username='" + username + "' AND password='" + password + "'");

                        if (rs.next()) {

                            setVisible(false);
                            flog.setVisible(false);
                            Home dr = new Home();

                            dr.jButton4.setVisible(false);
                            dr.jButton5.setVisible(false);
                            dr.jButton2.setVisible(false);
                            dr.jButton1.setVisible(false);
                            dr.jButton3.setVisible(false);
                            dr.jButton10.setVisible(false);
                            dr.jButton11.setVisible(false);
                            
                            dr.setHome("Patient");
                            dr.setVisible(true);

                        } else if ((jTextField1.getText().length() == 0) || (jPasswordField1.getText().length() == 0)) {
                            JOptionPane.showMessageDialog(null, "Entry Field is empty");
                        } else {
                            JOptionPane.showMessageDialog(null, "Incorrect username or password");
                            jTextField1.setText("");
                            jPasswordField1.setText("");
                        }

                    } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "Login Successfully");
                    }
                }
                case "Registeration" -> {
                    String firstname = jTextField2.getText();
                    String lastname = jTextField3.getText();
                    String contactNumber = jTextField4.getText();
                    try {

                        Connection con = ConnectionProvider.getcon();
                        Statement st = con.createStatement();
                        st.executeUpdate("insert into userlogin values('" + firstname + "','" + lastname + "','" + contactNumber + "','" + username + "','" + password + "')");
                        JOptionPane.showMessageDialog(null, "Successfully Update");
                        setVisible(false);
                        Login log = new Login();
                        log.setVisible(true);
                        log.jLabel5.setText("Patient Login");
                        log.jButton3.setVisible(true);
                        frontPage flogin = new frontPage();
                        log.setlogin("Patient", flogin);
                    } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(null, "Enter the data in correct formate");
                    }
                }
                default -> {
                }
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.jLabel5.setText("Register now");
        login.jButton1.setText("Save");
        login.jLabel3.setVisible(true);
        login.jLabel6.setVisible(true);
        login.jLabel7.setVisible(true);
        login.jTextField2.setVisible(true);
        login.jTextField3.setVisible(true);
        login.jTextField4.setVisible(true);
        login.setlog = "Registeration";
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
